"""users table

Revision ID: c9c0ea54255c
Revises: 
Create Date: 2020-07-21 13:46:32.680000

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c9c0ea54255c'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('model',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=64), nullable=True),
    sa.Column('email', sa.String(length=120), nullable=True),
    sa.Column('password_hash', sa.String(length=128), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_model_email'), 'model', ['email'], unique=True)
    op.create_index(op.f('ix_model_username'), 'model', ['username'], unique=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_model_username'), table_name='model')
    op.drop_index(op.f('ix_model_email'), table_name='model')
    op.drop_table('model')
    # ### end Alembic commands ###
